"""Deterministic source-URL generators for working public source types.

This module is template application, not an intelligent discovery agent. For
each watched company/product it generates canonical source candidates using
fixed URL patterns that the pipeline can scan today.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CandidateSource:
    """A URL candidate generated by a source template."""

    locator: str
    source_type: str
    source_family: str
    # True for sources accessible without account gating or a paid proxy.
    is_gate_free: bool
    enabled: bool = True
    tier: int | None = None
    signal_quality_score: float | None = None
    access_mode: str = "unknown"
    requires_proxy: bool = False
    requires_auth: bool = False
    recommended_cadence: str | None = None


def github_issues(repo_slug: str) -> CandidateSource:
    """GitHub Issues for a public repo, e.g. 'vercel/next.js'."""
    encoded_repo = repo_slug.strip()
    return CandidateSource(
        locator=(
            "https://api.github.com/search/issues"
            f"?q=repo:{encoded_repo}+is%3Aissue&sort=updated&order=desc"
        ),
        source_type="github_issues_search",
        source_family="technical_forum",
        is_gate_free=True,
        tier=1,
        signal_quality_score=0.95,
        access_mode="api",
        recommended_cadence="daily",
    )


def hackernews_search(query: str) -> CandidateSource:
    """Hacker News Algolia search — gate-free, generous rate limits."""
    encoded = query.replace(" ", "+")
    return CandidateSource(
        locator=(
            f"https://hn.algolia.com/api/v1/search_by_date"
            f"?query={encoded}&tags=comment&hitsPerPage=25"
        ),
        source_type="hackernews_search",
        source_family="technical_forum",
        is_gate_free=True,
        tier=2,
        signal_quality_score=0.78,
        access_mode="api",
        recommended_cadence="daily",
    )


def stackoverflow_search(query: str) -> CandidateSource:
    """Stack Overflow search — gate-free public API."""
    encoded = query.replace(" ", "+")
    return CandidateSource(
        locator=(
            f"https://api.stackexchange.com/2.3/search/advanced"
            f"?q={encoded}&site=stackoverflow&order=desc&sort=creation&pagesize=25"
        ),
        source_type="stackoverflow_search",
        source_family="technical_forum",
        is_gate_free=True,
        tier=1,
        signal_quality_score=0.95,
        access_mode="api",
        recommended_cadence="daily",
    )


def discourse_forum(base_url: str) -> CandidateSource:
    """A product's Discourse forum — gate-free if the forum is public."""
    base = base_url.rstrip("/")
    return CandidateSource(
        locator=f"{base}/latest.json?order=created",
        source_type="discourse_forum",
        source_family="technical_forum",
        is_gate_free=True,
        tier=2,
        signal_quality_score=0.82,
        access_mode="json",
        recommended_cadence="daily",
    )


def generate_company_sources(
    company_name: str,
    *,
    github_repo: str | None = None,
    discourse_url: str | None = None,
    include_stackoverflow: bool = False,
) -> list[CandidateSource]:
    """Generate all candidate sources for one company.

    Always includes Hacker News search as a starter source. Adds optional
    sources based on provided metadata.
    """
    sources: list[CandidateSource] = [
        hackernews_search(company_name),
    ]
    if github_repo:
        sources.append(github_issues(github_repo))
    if discourse_url:
        sources.append(discourse_forum(discourse_url))
    if include_stackoverflow:
        sources.append(stackoverflow_search(company_name))
    return sources
