"""Focused watchlist seed definitions.

The seed set is intentionally small and uses only source types that are part of
the current core loop: GitHub issues, Hacker News, public Discourse/community
forums, and Stack Overflow.
"""
from __future__ import annotations

NICHE_SEEDS: list[dict] = [
    {
        "job": "Track customer complaints about internal tool builders",
        "buyer": "Product teams evaluating internal tool platforms",
        "category": "devtools",
        "tools": [
            {"name": "Retool", "website": "https://retool.com"},
            {"name": "Appsmith", "website": "https://www.appsmith.com"},
            {"name": "Budibase", "website": "https://budibase.com"},
            {"name": "ToolJet", "website": "https://www.tooljet.com"},
        ],
        "sources": [
            {
                "locator": "https://api.github.com/search/issues?q=repo:appsmithorg/appsmith+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:Budibase/budibase+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:ToolJet/ToolJet+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://community.retool.com/latest.json",
                "source_type": "discourse",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "json",
                "tier": 2,
                "signal_quality_score": 0.82,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=retool+appsmith+budibase&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://api.stackexchange.com/2.3/search/advanced?q=internal+tools+admin+panel&site=stackoverflow&order=desc&sort=creation&pagesize=25",
                "source_type": "stackoverflow_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
        ],
    },
    {
        "job": "Track customer complaints about managed Postgres platforms",
        "buyer": "Engineering teams choosing hosted Postgres",
        "category": "devtools",
        "tools": [
            {"name": "Supabase", "website": "https://supabase.com"},
            {"name": "Neon", "website": "https://neon.tech"},
            {"name": "Railway", "website": "https://railway.app"},
            {"name": "Render", "website": "https://render.com"},
        ],
        "sources": [
            {
                "locator": "https://api.github.com/search/issues?q=repo:supabase/supabase+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:neondatabase/neon+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=supabase+postgres&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=neon+postgres&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://api.stackexchange.com/2.3/search/advanced?q=managed+postgres+database&site=stackoverflow&order=desc&sort=creation&pagesize=25",
                "source_type": "stackoverflow_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
        ],
    },
    {
        "job": "Track customer complaints about feature flag platforms",
        "buyer": "Product engineering teams managing releases",
        "category": "devtools",
        "tools": [
            {"name": "LaunchDarkly", "website": "https://launchdarkly.com"},
            {"name": "Flagsmith", "website": "https://www.flagsmith.com"},
            {"name": "Unleash", "website": "https://www.getunleash.io"},
            {"name": "PostHog", "website": "https://posthog.com"},
        ],
        "sources": [
            {
                "locator": "https://api.github.com/search/issues?q=repo:Flagsmith/flagsmith+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:Unleash/unleash+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:PostHog/posthog+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=launchdarkly+feature+flags&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://api.stackexchange.com/2.3/search/advanced?q=feature+flags+launchdarkly&site=stackoverflow&order=desc&sort=creation&pagesize=25",
                "source_type": "stackoverflow_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
        ],
    },
    {
        "job": "Track customer complaints about API development tools",
        "buyer": "Backend teams choosing API tooling",
        "category": "devtools",
        "tools": [
            {"name": "Postman", "website": "https://www.postman.com"},
            {"name": "Insomnia", "website": "https://insomnia.rest"},
            {"name": "Bruno", "website": "https://www.usebruno.com"},
            {"name": "Hoppscotch", "website": "https://hoppscotch.io"},
        ],
        "sources": [
            {
                "locator": "https://api.github.com/search/issues?q=repo:usebruno/bruno+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=repo:hoppscotch/hoppscotch+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=postman+api&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=bruno+api+client&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://api.stackexchange.com/2.3/search/advanced?q=postman+api+client&site=stackoverflow&order=desc&sort=creation&pagesize=25",
                "source_type": "stackoverflow_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
        ],
    },
    {
        "job": "Track customer complaints about podcast hosting platforms",
        "buyer": "Creators and media teams choosing podcast tools",
        "category": "creator_tools",
        "tools": [
            {"name": "Riverside", "website": "https://riverside.fm"},
            {"name": "Descript", "website": "https://www.descript.com"},
            {"name": "Transistor", "website": "https://transistor.fm"},
            {"name": "Buzzsprout", "website": "https://www.buzzsprout.com"},
        ],
        "sources": [
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=riverside+podcast&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=descript+podcast&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://hn.algolia.com/api/v1/search_by_date?query=podcast+hosting+platform&tags=comment",
                "source_type": "hackernews",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 2,
                "signal_quality_score": 0.78,
            },
            {
                "locator": "https://api.stackexchange.com/2.3/search/advanced?q=podcast+hosting+audio+workflow&site=stackoverflow&order=desc&sort=creation&pagesize=25",
                "source_type": "stackoverflow_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.95,
            },
            {
                "locator": "https://api.github.com/search/issues?q=podcast+hosting+is%3Aissue&sort=updated&order=desc",
                "source_type": "github_issues_search",
                "source_family": "technical_forum",
                "is_gate_free": True,
                "access_mode": "api",
                "tier": 1,
                "signal_quality_score": 0.7,
            },
        ],
    },
]
