"""Niche seed definitions — version-controlled, never hand-entered in Supabase.

Format for each seed entry:
{
    "job":      str,            # job-to-be-done, phrased as an outcome
    "buyer":    str,            # who has this job
    "category": str,            # broad grouping (devtools, no_code, vertical_saas, ...)
    "tools": [                  # competing tools for this job
        {
            "name":    str,
            "website": str | None,
        }
    ],
    "sources": [                # OPTIONAL — a niche can be seeded with zero sources
        {
            "locator":       str,
            "source_type":   str,
            "source_family": str,
            "is_gate_free":  bool,
        }
    ],
}

A niche seeded with no sources starts in 'defined' status.
A niche seeded with sources starts in 'sourced' status.
"""
from __future__ import annotations

NICHE_SEEDS: list[dict] = [
    # ── No-code ──────────────────────────────────────────────────────────────
    {
        "job": "Build a customer-facing web app without code",
        "buyer": "Non-technical founders",
        "category": "no_code",
        "tools": [
            {"name": "Bubble", "website": "https://bubble.io"},
            {"name": "Webflow", "website": "https://webflow.com"},
            {"name": "Softr", "website": "https://www.softr.io"},
            {"name": "FlutterFlow", "website": "https://flutterflow.io"},
            {"name": "WeWeb", "website": "https://www.weweb.io"},
            {"name": "Adalo", "website": "https://www.adalo.com"},
        ],
        "sources": [
            {"locator": "https://forum.bubble.io/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://forum.webflow.com/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=bubble.io&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=webflow&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/bubble", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/nocode", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/webflow", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Build a mobile app without code",
        "buyer": "Solo founders, small teams",
        "category": "no_code",
        "tools": [
            {"name": "FlutterFlow", "website": "https://flutterflow.io"},
            {"name": "Glide", "website": "https://www.glideapps.com"},
            {"name": "Adalo", "website": "https://www.adalo.com"},
            {"name": "Draftbit", "website": "https://draftbit.com"},
            {"name": "Thunkable", "website": "https://thunkable.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=flutterflow&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=glide+apps&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/FlutterFlow", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/nocode", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Devtools ─────────────────────────────────────────────────────────────
    {
        "job": "Build internal tools and admin panels over a database",
        "buyer": "Engineering and ops teams",
        "category": "devtools",
        "tools": [
            {"name": "Retool", "website": "https://retool.com"},
            {"name": "Appsmith", "website": "https://www.appsmith.com"},
            {"name": "Budibase", "website": "https://budibase.com"},
            {"name": "ToolJet", "website": "https://www.tooljet.com"},
            {"name": "UI Bakery", "website": "https://uibakery.io"},
            {"name": "Internal", "website": "https://www.internal.io"},
        ],
        "sources": [
            {"locator": "https://github.com/appsmithorg/appsmith/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/Budibase/budibase/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/ToolJet/ToolJet/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://community.retool.com/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=retool&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/lowcode", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Deploy and host a web frontend without DevOps",
        "buyer": "Web developers, indie hackers",
        "category": "devtools",
        "tools": [
            {"name": "Vercel", "website": "https://vercel.com"},
            {"name": "Netlify", "website": "https://www.netlify.com"},
            {"name": "Cloudflare Pages", "website": "https://pages.cloudflare.com"},
            {"name": "Render", "website": "https://render.com"},
            {"name": "Railway", "website": "https://railway.app"},
            {"name": "Fly.io", "website": "https://fly.io"},
        ],
        "sources": [
            {"locator": "https://community.vercel.com/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://community.fly.io/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=vercel&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=railway.app&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/nextjs", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/webdev", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run a managed Postgres database for an app",
        "buyer": "Full-stack developers",
        "category": "devtools",
        "tools": [
            {"name": "Supabase", "website": "https://supabase.com"},
            {"name": "Neon", "website": "https://neon.tech"},
            {"name": "Railway", "website": "https://railway.app"},
            {"name": "Render", "website": "https://render.com"},
            {"name": "Crunchy Bridge", "website": "https://www.crunchybridge.com"},
            {"name": "Aiven", "website": "https://aiven.io"},
        ],
        "sources": [
            {"locator": "https://github.com/supabase/supabase/discussions", "source_type": "github_discussions", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/neondatabase/neon/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=supabase&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=neon+postgres&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/PostgreSQL", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Supabase", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Catch and triage application errors in production",
        "buyer": "Backend and SRE engineers",
        "category": "devtools",
        "tools": [
            {"name": "Sentry", "website": "https://sentry.io"},
            {"name": "Datadog", "website": "https://www.datadoghq.com"},
            {"name": "New Relic", "website": "https://newrelic.com"},
            {"name": "Rollbar", "website": "https://rollbar.com"},
            {"name": "Bugsnag", "website": "https://www.bugsnag.com"},
            {"name": "Honeybadger", "website": "https://www.honeybadger.io"},
        ],
        "sources": [
            {"locator": "https://github.com/getsentry/sentry/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=sentry+errors&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=datadog&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://api.stackexchange.com/2.3/questions?tagged=sentry&site=stackoverflow", "source_type": "stackoverflow", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/devops", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run CI/CD pipelines to ship code",
        "buyer": "DevOps engineers",
        "category": "devtools",
        "tools": [
            {"name": "GitHub Actions", "website": "https://github.com/features/actions"},
            {"name": "GitLab CI", "website": "https://docs.gitlab.com/ee/ci"},
            {"name": "CircleCI", "website": "https://circleci.com"},
            {"name": "Buildkite", "website": "https://buildkite.com"},
            {"name": "Jenkins", "website": "https://www.jenkins.io"},
            {"name": "Drone", "website": "https://www.drone.io"},
        ],
        "sources": [
            {"locator": "https://github.com/actions/runner/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=github+actions&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=circleci&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://api.stackexchange.com/2.3/questions?tagged=github-actions&site=stackoverflow", "source_type": "stackoverflow", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/devops", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Develop and test APIs",
        "buyer": "Backend developers, QA engineers",
        "category": "devtools",
        "tools": [
            {"name": "Postman", "website": "https://www.postman.com"},
            {"name": "Insomnia", "website": "https://insomnia.rest"},
            {"name": "Hoppscotch", "website": "https://hoppscotch.io"},
            {"name": "Bruno", "website": "https://www.usebruno.com"},
            {"name": "Thunder Client", "website": "https://www.thunderclient.com"},
        ],
        "sources": [
            {"locator": "https://github.com/usebruno/bruno/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/hoppscotch/hoppscotch/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=postman+api&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=bruno+api&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/Postman", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Roll out features behind flags",
        "buyer": "Platform and product engineers",
        "category": "devtools",
        "tools": [
            {"name": "LaunchDarkly", "website": "https://launchdarkly.com"},
            {"name": "Flagsmith", "website": "https://www.flagsmith.com"},
            {"name": "Unleash", "website": "https://www.getunleash.io"},
            {"name": "Split", "website": "https://www.split.io"},
            {"name": "ConfigCat", "website": "https://configcat.com"},
            {"name": "PostHog", "website": "https://posthog.com"},
        ],
        "sources": [
            {"locator": "https://github.com/Unleash/unleash/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/Flagsmith/flagsmith/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/PostHog/posthog/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=launchdarkly&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=feature+flags&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
        ],
    },
    # ── Automation ───────────────────────────────────────────────────────────
    {
        "job": "Automate workflows between SaaS apps",
        "buyer": "RevOps, agency owners",
        "category": "automation",
        "tools": [
            {"name": "Zapier", "website": "https://zapier.com"},
            {"name": "Make", "website": "https://www.make.com"},
            {"name": "n8n", "website": "https://n8n.io"},
            {"name": "Pipedream", "website": "https://pipedream.com"},
            {"name": "Workato", "website": "https://www.workato.com"},
            {"name": "Activepieces", "website": "https://www.activepieces.com"},
        ],
        "sources": [
            {"locator": "https://github.com/n8n-io/n8n/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/activepieces/activepieces/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://community.n8n.io/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=zapier&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/zapier", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/nocode", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Data ─────────────────────────────────────────────────────────────────
    {
        "job": "Build BI dashboards on a database",
        "buyer": "Data analysts",
        "category": "data",
        "tools": [
            {"name": "Metabase", "website": "https://www.metabase.com"},
            {"name": "Apache Superset", "website": "https://superset.apache.org"},
            {"name": "Tableau", "website": "https://www.tableau.com"},
            {"name": "Power BI", "website": "https://powerbi.microsoft.com"},
            {"name": "Looker Studio", "website": "https://cloud.google.com/looker-studio"},
            {"name": "Hex", "website": "https://hex.tech"},
            {"name": "Sigma", "website": "https://www.sigmacomputing.com"},
        ],
        "sources": [
            {"locator": "https://github.com/metabase/metabase/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/apache/superset/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://discourse.metabase.com/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=metabase&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/BusinessIntelligence", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/tableau", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Transform data in the warehouse (analytics engineering)",
        "buyer": "Analytics engineers",
        "category": "data",
        "tools": [
            {"name": "dbt", "website": "https://www.getdbt.com"},
            {"name": "SQLMesh", "website": "https://sqlmesh.com"},
            {"name": "Dataform", "website": "https://dataform.co"},
            {"name": "Coalesce", "website": "https://coalesce.io"},
        ],
        "sources": [
            {"locator": "https://github.com/dbt-labs/dbt-core/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/TobikoData/sqlmesh/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://discourse.getdbt.com/latest.json", "source_type": "discourse", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=dbt+data&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/dataengineering", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Ingest and sync source data into a warehouse (ELT)",
        "buyer": "Data engineers",
        "category": "data",
        "tools": [
            {"name": "Fivetran", "website": "https://www.fivetran.com"},
            {"name": "Airbyte", "website": "https://airbyte.com"},
            {"name": "Meltano", "website": "https://meltano.com"},
            {"name": "Stitch", "website": "https://www.stitchdata.com"},
            {"name": "Hevo", "website": "https://hevodata.com"},
            {"name": "Portable", "website": "https://portable.io"},
        ],
        "sources": [
            {"locator": "https://github.com/airbytehq/airbyte/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/airbytehq/airbyte/discussions", "source_type": "github_discussions", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/meltano/meltano/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=fivetran&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/dataengineering", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Orchestrate data pipelines",
        "buyer": "Data engineers",
        "category": "data",
        "tools": [
            {"name": "Apache Airflow", "website": "https://airflow.apache.org"},
            {"name": "Prefect", "website": "https://www.prefect.io"},
            {"name": "Dagster", "website": "https://dagster.io"},
            {"name": "Mage", "website": "https://www.mage.ai"},
            {"name": "Kestra", "website": "https://kestra.io"},
        ],
        "sources": [
            {"locator": "https://github.com/apache/airflow/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/dagster-io/dagster/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/PrefectHQ/prefect/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/kestra-io/kestra/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=airflow+orchestration&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/dataengineering", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Sales ─────────────────────────────────────────────────────────────────
    {
        "job": "Find verified B2B contact data for outreach",
        "buyer": "SDRs, sales teams",
        "category": "sales",
        "tools": [
            {"name": "Apollo.io", "website": "https://www.apollo.io"},
            {"name": "ZoomInfo", "website": "https://www.zoominfo.com"},
            {"name": "Clay", "website": "https://www.clay.com"},
            {"name": "Hunter.io", "website": "https://hunter.io"},
            {"name": "Lusha", "website": "https://www.lusha.com"},
            {"name": "Cognism", "website": "https://www.cognism.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=apollo.io&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=zoominfo&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=apollo.io", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/sales", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/coldemail", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run cold-email outreach sequences at scale",
        "buyer": "SDRs, lead-gen agencies",
        "category": "sales",
        "tools": [
            {"name": "Instantly", "website": "https://instantly.ai"},
            {"name": "Smartlead", "website": "https://www.smartlead.ai"},
            {"name": "Lemlist", "website": "https://www.lemlist.com"},
            {"name": "Mailshake", "website": "https://mailshake.com"},
            {"name": "Reply.io", "website": "https://reply.io"},
            {"name": "Woodpecker", "website": "https://woodpecker.co"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=cold+email&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=instantly", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.g2.com/search?query=smartlead", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/coldemail", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Emailmarketing", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run a CRM and sales pipeline for a small team",
        "buyer": "SMB sales teams, founders",
        "category": "sales",
        "tools": [
            {"name": "HubSpot", "website": "https://www.hubspot.com"},
            {"name": "Pipedrive", "website": "https://www.pipedrive.com"},
            {"name": "Attio", "website": "https://attio.com"},
            {"name": "Folk", "website": "https://www.folk.app"},
            {"name": "Close", "website": "https://www.close.com"},
            {"name": "Copper", "website": "https://www.copper.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=hubspot+crm&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=attio&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=hubspot", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.g2.com/search?query=pipedrive", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/CRM", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/sales", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Schedule meetings without back-and-forth",
        "buyer": "Salespeople, consultants",
        "category": "sales",
        "tools": [
            {"name": "Calendly", "website": "https://calendly.com"},
            {"name": "Cal.com", "website": "https://cal.com"},
            {"name": "SavvyCal", "website": "https://savvycal.com"},
            {"name": "Acuity Scheduling", "website": "https://acuityscheduling.com"},
            {"name": "Chili Piper", "website": "https://www.chilipiper.com"},
        ],
        "sources": [
            {"locator": "https://github.com/calcom/cal.com/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=calendly&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=cal.com&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=calendly", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
        ],
    },
    # ── Marketing ─────────────────────────────────────────────────────────────
    {
        "job": "Schedule and publish social media posts",
        "buyer": "Social media managers, agencies",
        "category": "marketing",
        "tools": [
            {"name": "Buffer", "website": "https://buffer.com"},
            {"name": "Hootsuite", "website": "https://www.hootsuite.com"},
            {"name": "Later", "website": "https://later.com"},
            {"name": "Publer", "website": "https://publer.io"},
            {"name": "Metricool", "website": "https://metricool.com"},
            {"name": "SocialBee", "website": "https://socialbee.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/search?query=buffer", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.g2.com/search?query=hootsuite", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/SocialMediaMarketing", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/socialmedia", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Build forms to capture leads and data",
        "buyer": "Marketers, ops teams",
        "category": "marketing",
        "tools": [
            {"name": "Typeform", "website": "https://www.typeform.com"},
            {"name": "Tally", "website": "https://tally.so"},
            {"name": "Jotform", "website": "https://www.jotform.com"},
            {"name": "Fillout", "website": "https://www.fillout.com"},
            {"name": "Paperform", "website": "https://paperform.co"},
            {"name": "Formstack", "website": "https://www.formstack.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=typeform&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=tally+forms&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=typeform", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/nocode", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run email newsletters and marketing campaigns",
        "buyer": "Creators, marketers",
        "category": "marketing",
        "tools": [
            {"name": "Mailchimp", "website": "https://mailchimp.com"},
            {"name": "Kit (ConvertKit)", "website": "https://kit.com"},
            {"name": "Beehiiv", "website": "https://www.beehiiv.com"},
            {"name": "Substack", "website": "https://substack.com"},
            {"name": "ActiveCampaign", "website": "https://www.activecampaign.com"},
            {"name": "MailerLite", "website": "https://www.mailerlite.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=beehiiv&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=mailchimp&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=mailchimp", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Emailmarketing", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/newsletters", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Measure product and marketing analytics",
        "buyer": "Growth marketers, product teams",
        "category": "marketing",
        "tools": [
            {"name": "PostHog", "website": "https://posthog.com"},
            {"name": "Mixpanel", "website": "https://mixpanel.com"},
            {"name": "Amplitude", "website": "https://amplitude.com"},
            {"name": "Plausible", "website": "https://plausible.io"},
            {"name": "Fathom", "website": "https://usefathom.com"},
            {"name": "Heap", "website": "https://heap.io"},
        ],
        "sources": [
            {"locator": "https://github.com/PostHog/posthog/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://github.com/plausible/analytics/issues", "source_type": "github_issues", "source_family": "technical_forum", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=mixpanel&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=amplitude+analytics&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.reddit.com/r/analytics", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Do keyword research and track SEO rankings",
        "buyer": "SEO specialists, agencies",
        "category": "marketing",
        "tools": [
            {"name": "Ahrefs", "website": "https://ahrefs.com"},
            {"name": "Semrush", "website": "https://www.semrush.com"},
            {"name": "Moz", "website": "https://moz.com"},
            {"name": "SE Ranking", "website": "https://seranking.com"},
            {"name": "Surfer SEO", "website": "https://surferseo.com"},
            {"name": "Mangools", "website": "https://mangools.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/search?query=ahrefs", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.g2.com/search?query=semrush", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/SEO", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/bigseo", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/juststart", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Customer support ──────────────────────────────────────────────────────
    {
        "job": "Run a customer-support ticketing helpdesk",
        "buyer": "Support leads",
        "category": "customer_support",
        "tools": [
            {"name": "Zendesk", "website": "https://www.zendesk.com"},
            {"name": "Intercom", "website": "https://www.intercom.com"},
            {"name": "Freshdesk", "website": "https://freshdesk.com"},
            {"name": "Help Scout", "website": "https://www.helpscout.com"},
            {"name": "Front", "website": "https://front.com"},
            {"name": "Gorgias", "website": "https://www.gorgias.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=zendesk&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=intercom&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=zendesk", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.g2.com/search?query=intercom", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/CustomerSuccess", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Add an AI chat agent to handle support",
        "buyer": "Support and CX teams",
        "category": "customer_support",
        "tools": [
            {"name": "Intercom Fin", "website": "https://www.intercom.com/fin"},
            {"name": "Ada", "website": "https://www.ada.cx"},
            {"name": "Chatbase", "website": "https://www.chatbase.co"},
            {"name": "Forethought", "website": "https://forethought.ai"},
            {"name": "Crisp", "website": "https://crisp.chat"},
            {"name": "Tidio", "website": "https://www.tidio.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=intercom+fin&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=ai+support+agent&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=ada+support", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/CustomerSuccess", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Build a self-serve help center and knowledge base",
        "buyer": "Support and docs teams",
        "category": "customer_support",
        "tools": [
            {"name": "Document360", "website": "https://document360.com"},
            {"name": "GitBook", "website": "https://www.gitbook.com"},
            {"name": "Helpjuice", "website": "https://helpjuice.com"},
            {"name": "Guru", "website": "https://www.getguru.com"},
            {"name": "Slab", "website": "https://slab.com"},
        ],
        "sources": [
            {"locator": "https://hn.algolia.com/api/v1/search_by_date?query=gitbook&tags=story", "source_type": "hackernews", "source_family": "search", "is_gate_free": True},
            {"locator": "https://www.g2.com/search?query=document360", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/technicalwriting", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Vertical SaaS ─────────────────────────────────────────────────────────
    {
        "job": "Run a small law firm (case management and billing)",
        "buyer": "Solo and small-firm attorneys",
        "category": "vertical_saas",
        "tools": [
            {"name": "Clio", "website": "https://www.clio.com"},
            {"name": "MyCase", "website": "https://www.mycase.com"},
            {"name": "PracticePanther", "website": "https://www.practicepanther.com"},
            {"name": "Smokeball", "website": "https://www.smokeball.com"},
            {"name": "CosmoLex", "website": "https://www.cosmolex.com"},
            {"name": "Filevine", "website": "https://www.filevine.com"},
            {"name": "Rocket Matter", "website": "https://www.rocketmatter.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/legal-case-management", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/legal-case-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/LawFirm", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Lawyertalk", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage the contract lifecycle (CLM)",
        "buyer": "In-house legal, legal ops",
        "category": "vertical_saas",
        "tools": [
            {"name": "Ironclad", "website": "https://ironcladapp.com"},
            {"name": "Juro", "website": "https://juro.com"},
            {"name": "LinkSquares", "website": "https://linksquares.com"},
            {"name": "ContractWorks", "website": "https://www.contractworks.com"},
            {"name": "Concord", "website": "https://www.concord.app"},
            {"name": "Agiloft", "website": "https://www.agiloft.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/contract-lifecycle-management-clm", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/contract-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/legaltech", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run a solo therapy practice (EHR and billing)",
        "buyer": "Solo therapists, counselors",
        "category": "vertical_saas",
        "tools": [
            {"name": "SimplePractice", "website": "https://www.simplepractice.com"},
            {"name": "TherapyNotes", "website": "https://www.therapynotes.com"},
            {"name": "TheraNest", "website": "https://theranest.com"},
            {"name": "Jane App", "website": "https://jane.app"},
            {"name": "Healthie", "website": "https://www.gethealthie.com"},
            {"name": "IntakeQ", "website": "https://intakeq.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/mental-health", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/mental-health-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/therapists", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run a dental practice",
        "buyer": "Dental office managers",
        "category": "vertical_saas",
        "tools": [
            {"name": "Dentrix", "website": "https://www.dentrix.com"},
            {"name": "Eaglesoft", "website": "https://www.pattersondental.com/software/eaglesoft"},
            {"name": "Open Dental", "website": "https://www.opendental.com"},
            {"name": "Curve Dental", "website": "https://www.curvedental.com"},
            {"name": "Denticon", "website": "https://www.planetdds.com/denticon"},
            {"name": "tab32", "website": "https://www.tab32.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/dental-practice-management", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/dental-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.dentaltown.com", "source_type": "forum", "source_family": "technical_forum", "is_gate_free": True},
        ],
    },
    {
        "job": "Run a home field-service business (HVAC, plumbing, electrical)",
        "buyer": "Home-service business owners",
        "category": "vertical_saas",
        "tools": [
            {"name": "ServiceTitan", "website": "https://www.servicetitan.com"},
            {"name": "Housecall Pro", "website": "https://www.housecallpro.com"},
            {"name": "Jobber", "website": "https://getjobber.com"},
            {"name": "FieldEdge", "website": "https://fieldedge.com"},
            {"name": "ServiceM8", "website": "https://www.servicem8.com"},
            {"name": "Workiz", "website": "https://www.workiz.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/field-service-management-fsm", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/field-service-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/HVAC", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Plumbing", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/electricians", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage construction projects and bids",
        "buyer": "General contractors, builders",
        "category": "vertical_saas",
        "tools": [
            {"name": "Procore", "website": "https://www.procore.com"},
            {"name": "Buildertrend", "website": "https://buildertrend.com"},
            {"name": "Autodesk Construction Cloud", "website": "https://construction.autodesk.com"},
            {"name": "Fieldwire", "website": "https://www.fieldwire.com"},
            {"name": "Knowify", "website": "https://www.knowify.com"},
            {"name": "JobTread", "website": "https://www.jobtread.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/construction-management", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/construction-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Construction", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Contractor", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage real estate leads and transactions",
        "buyer": "Real estate agents",
        "category": "vertical_saas",
        "tools": [
            {"name": "Follow Up Boss", "website": "https://www.followupboss.com"},
            {"name": "kvCORE", "website": "https://www.insiderealestate.com/kvcore"},
            {"name": "BoomTown", "website": "https://boomtownroi.com"},
            {"name": "Lofty", "website": "https://lofty.com"},
            {"name": "LionDesk", "website": "https://www.liondesk.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/real-estate-crm", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/real-estate-crm-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/realtors", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage long-term rental property",
        "buyer": "Landlords, property managers",
        "category": "vertical_saas",
        "tools": [
            {"name": "Buildium", "website": "https://www.buildium.com"},
            {"name": "AppFolio", "website": "https://www.appfolio.com"},
            {"name": "DoorLoop", "website": "https://www.doorloop.com"},
            {"name": "TenantCloud", "website": "https://www.tenantcloud.com"},
            {"name": "RentRedi", "website": "https://www.rentredi.com"},
            {"name": "Stessa", "website": "https://www.stessa.com"},
            {"name": "Hemlane", "website": "https://www.hemlane.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/property-management", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/property-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/Landlord", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/realestateinvesting", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage short-term rentals (Airbnb, VRBO)",
        "buyer": "STR hosts, property managers",
        "category": "vertical_saas",
        "tools": [
            {"name": "Hospitable", "website": "https://hospitable.com"},
            {"name": "Guesty", "website": "https://www.guesty.com"},
            {"name": "Hostaway", "website": "https://www.hostaway.com"},
            {"name": "Lodgify", "website": "https://www.lodgify.com"},
            {"name": "OwnerRez", "website": "https://www.ownerrez.com"},
            {"name": "iGMS", "website": "https://www.igms.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/vacation-rental", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/vacation-rental-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/airbnb_hosts", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/ShortTermRentals", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Run a restaurant POS and operations",
        "buyer": "Restaurant owners",
        "category": "vertical_saas",
        "tools": [
            {"name": "Toast", "website": "https://pos.toasttab.com"},
            {"name": "Square for Restaurants", "website": "https://squareup.com/us/en/point-of-sale/restaurants"},
            {"name": "Clover", "website": "https://www.clover.com"},
            {"name": "TouchBistro", "website": "https://www.touchbistro.com"},
            {"name": "Lightspeed", "website": "https://www.lightspeedhq.com"},
            {"name": "SpotOn", "website": "https://www.spoton.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/restaurant-pos", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/restaurant-pos-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/restaurateur", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    {
        "job": "Manage gym memberships and bookings",
        "buyer": "Gym and studio owners",
        "category": "vertical_saas",
        "tools": [
            {"name": "Mindbody", "website": "https://www.mindbodyonline.com"},
            {"name": "Zen Planner", "website": "https://zenplanner.com"},
            {"name": "PushPress", "website": "https://www.pushpress.com"},
            {"name": "Wodify", "website": "https://www.wodify.com"},
            {"name": "Gymdesk", "website": "https://gymdesk.com"},
        ],
        "sources": [
            {"locator": "https://www.g2.com/categories/club-management", "source_type": "g2", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.capterra.com/gym-management-software/", "source_type": "capterra", "source_family": "reviews", "is_gate_free": False},
            {"locator": "https://www.reddit.com/r/crossfitowners", "source_type": "reddit", "source_family": "social", "is_gate_free": False},
        ],
    },
    # ── Truncated — paste remaining niches here ───────────────────────────────
]
