"""Application persistence ports."""
from application.ports.repositories import (
    AgentActionRepository,
    AgentActivityRepository,
    AgentAlertRepository,
    AgentFeedbackRepository,
    AgentFollowUpRepository,
    AgentPreferencesRepository,
    ClusterRepository,
    GapRepository,
    NicheCompanyRepository,
    NicheRepository,
    NicheSourceRepository,
    OpportunityRepository,
    PipelineRunMetricsRepository,
    PostRepository,
    ScoreRepository,
    SignalRepository,
    SourceLocatorRepository,
    UserNicheRepository,
)

__all__ = [
    "ClusterRepository",
    "AgentActionRepository",
    "AgentActivityRepository",
    "AgentAlertRepository",
    "AgentFeedbackRepository",
    "AgentFollowUpRepository",
    "AgentPreferencesRepository",
    "GapRepository",
    "NicheCompanyRepository",
    "NicheRepository",
    "NicheSourceRepository",
    "OpportunityRepository",
    "PipelineRunMetricsRepository",
    "PostRepository",
    "ScoreRepository",
    "SignalRepository",
    "SourceLocatorRepository",
    "UserNicheRepository",
]
