"""Application persistence ports."""
from application.ports.repositories import (
    AgentActivityRepository,
    AgentFeedbackRepository,
    AgentPreferencesRepository,
    ClusterRepository,
    FindingRepository,
    NicheCompanyRepository,
    NicheRepository,
    OpportunityRepository,
    PipelineRunMetricsRepository,
    PostRepository,
    ScoreRepository,
    SignalRepository,
    SourceRepository,
    SourceLocatorRepository,
    TemplateSourceBindingRepository,
    ThemeRepository,
    UserNicheRepository,
    UserSourceRepository,
    UserSourcePreferenceRepository,
    UserSourceRunStatsRepository,
)

__all__ = [
    "ClusterRepository",
    "AgentActivityRepository",
    "AgentFeedbackRepository",
    "AgentPreferencesRepository",
    "FindingRepository",
    "NicheCompanyRepository",
    "NicheRepository",
    "OpportunityRepository",
    "PipelineRunMetricsRepository",
    "PostRepository",
    "ScoreRepository",
    "SignalRepository",
    "SourceRepository",
    "SourceLocatorRepository",
    "TemplateSourceBindingRepository",
    "ThemeRepository",
    "UserNicheRepository",
    "UserSourceRepository",
    "UserSourcePreferenceRepository",
    "UserSourceRunStatsRepository",
]
